INFO 2022-09-11 16:56:12,712 - Start time: 20220911T165612
WARNING 2022-09-11 16:56:28,957 - Exception encountered in fetch_trial_data. Traceback: Traceback (most recent call last):
  File "/global/cscratch1/sd/yazbeck/boa/boa/metaclasses.py", line 19, in wrapper
    return func(*args, **kwargs)
  File "/global/cscratch1/sd/yazbeck/boa/boa/wrapper_utils.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/global/cscratch1/sd/yazbeck/US_LA3_Wetl_C3Gra_Trans/elm_wrapper.py", line 428, in fetch_trial_data
    y_pred, y_true = get_model_obs(
  File "/global/cscratch1/sd/yazbeck/US_LA3_Wetl_C3Gra_Trans/elm_wrapper.py", line 271, in get_model_obs
    modeldf["CH4_SURF_AERE_TOT"] = np.array(AllModelVar["CH4_SURF_AERE_SAT"])*np.array(AllModelVar["FINUNDATED"])+np.array(AllModelVar["CH4_SURF_AERE_UNSAT"])*(1-np.array(AllModelVar["FINUNDATED"]))
TypeError: can't multiply sequence by non-int of type 'list'

